"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const html=fs.readFileSync("app/static/chat.html","utf8");
const css=fs.readFileSync("app/static/nabil_reference_theme.css","utf8");
assert.match(html,/<aside class="lesson-tutor-card"/,"verify real lesson assistant");
assert.match(html,/<div class="lesson-avatar-live"/,"verify actual avatar wrapper");
assert.match(html,/src="\/static\/nabil-lesson-avatar\.png"/,"verify actual lesson avatar bitmap");
const mark=css.indexOf("OWNER_LESSON_AVATAR_FITS_CARD_V11");
assert(mark>=0,"new scoped fit rules required");
const patch=css.slice(mark);
assert(patch.includes("body.nabil-lesson-active .lesson-tutor-card .lesson-avatar-live{"),"scope only structured lesson");
assert(patch.includes("max-width:110px!important;max-height:110px!important"),"desktop avatar cap");
assert(patch.includes("width:62px!important;height:62px!important"),"phone avatar cap");
assert(patch.includes("width:56px!important;height:56px!important"),"narrow phone avatar cap");
assert(patch.includes("object-fit:contain!important;object-position:center center!important"),"whole robot in frame");
assert(patch.includes("max-width:100%!important;max-height:100%!important"),"bitmap confined to avatar frame");
assert(!patch.includes("body.nabil-home-lock .lesson-avatar-live"),"do not resize landing robot");
console.log("NABIL structured lesson avatar full-contain desktop and mobile selectors: PASS");
